// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR5qXTia1_7gGyU5rNgaGki8wCL5q3GAQ',
    appId: '1:697924663882:web:1fa26008c93568a8a6c4b3',
    messagingSenderId: '697924663882',
    projectId: 'chat-app-e0935',
    authDomain: 'chat-app-e0935.firebaseapp.com',
    storageBucket: 'chat-app-e0935.firebasestorage.app',
    measurementId: 'G-NFJVM6489P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTnwYR7kEEgyo2L2Is20O0ea1OuDLe978',
    appId: '1:697924663882:android:aef74b173b5be037a6c4b3',
    messagingSenderId: '697924663882',
    projectId: 'chat-app-e0935',
    storageBucket: 'chat-app-e0935.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnrWN0bApsxvILqxejmsr-WxSYfAug8Vc',
    appId: '1:697924663882:ios:9a77e9ee7e38d9fda6c4b3',
    messagingSenderId: '697924663882',
    projectId: 'chat-app-e0935',
    storageBucket: 'chat-app-e0935.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnrWN0bApsxvILqxejmsr-WxSYfAug8Vc',
    appId: '1:697924663882:ios:9a77e9ee7e38d9fda6c4b3',
    messagingSenderId: '697924663882',
    projectId: 'chat-app-e0935',
    storageBucket: 'chat-app-e0935.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR5qXTia1_7gGyU5rNgaGki8wCL5q3GAQ',
    appId: '1:697924663882:web:ae827759f076ff92a6c4b3',
    messagingSenderId: '697924663882',
    projectId: 'chat-app-e0935',
    authDomain: 'chat-app-e0935.firebaseapp.com',
    storageBucket: 'chat-app-e0935.firebasestorage.app',
    measurementId: 'G-7P79JZSHTY',
  );
}
